SELECT * FROM usuarios
SELECT * FROM tiposUsuarios
SELECT * FROM motoristas
SELECT * FROM tiposVeiculos
SELECT * FROM veiculos
SELECT * FROM imgVeiculos
SELECT * FROM situacoes
SELECT * FROM manutencoes
SELECT * FROM rotas
SELECT * FROM tiposPecas
SELECT * FROM Pecas
SELECT * FROM logAlteracao